name:  Documentaci贸n
description: Documentaci贸n
labels: [docs]
body:
  - type: textarea
    id: issue
    attributes:
      label: 驴Tema principal de la documentaci贸n?
      description: secci贸n del documento.
    validations:
      required: true
