name: 🚀 Feature Request
description: Nueva funcionalidad
labels: [feature]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Descripción de la funcionalidad que se va a agregar.
      placeholder: "Quiero que al hacer clic en X, suceda Y..."
    validations:
      required: true

  - type: input
    id: related
    attributes:
      label: ¿Está relacionado con algún issue existente?
      placeholder: "#123, #456"
    validations:
      required: false
